server:
  port: 8082

spring:
  application:
    name: pet-service

  datasource:
    url: jdbc:postgresql://ep-misty-bread-a8zqgwmk-pooler.eastus2.azure.neon.tech:5432/petdb?sslmode=require&channelBinding=require
    username: petdb_owner
    password: npg_VzZC8xHm7DAv
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
